name: Build and Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. SETUP PYTHON (For Django)
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 2. SETUP NODE & ANGULAR
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      # 3. INSTALL & BUILD (The fix for the folder error)
      - name: Install Angular Dependencies
        working-directory: ./lost_found
        run: npm install

      - name: Build Angular Project
        working-directory: ./lost_found
        run: ng build --configuration production
